name: Docker build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: docker login
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      
      - name: docker build
        run: |
          docker build . -t leofellipe/projeto-devops2:latest
      
      - name: docker push
        run: |
          docker push leofellipe/projeto-devops2:latest
  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - run: nodejs index.js

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker pull
        env: 
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker pull $DOCKERHUB_USER/projeto-devops2:latest
      - name: dokcer run
        run: |
          docker run --rm -d --name mycontainer -p 3000:3000 $DOCKERHUB_USER/projeto-devops2:latest
      - run: echo "Finalizado!"
